/**
 * Detect demo / mock Nimiq addresses generated by SteadyStreak.
 * Shared by client (skip public publish) and server (reject / filter).
 */

export const MOCK_ADDRESS_MARKERS = [
  "DEADBEEFCAFEDEMO",
  "A1B2C3D4E5F67890", // older generator
] as const;

export function isMockWalletAddress(address: string | null | undefined): boolean {
  if (!address) return false;
  const compact = address.replace(/\s+/g, "").toUpperCase();
  if (MOCK_ADDRESS_MARKERS.some((m) => compact.includes(m))) return true;
  // Intermediate generator padded with zeros → long 0000 runs in the payload
  const payload = compact.startsWith("NQ") ? compact.slice(4) : compact;
  if (/0{12,}/.test(payload)) return true;
  return false;
}
